### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xuexb** [52cik/btpl#1]
首先赞个~

建议代码加上`jshint`或者`jslint`检查，比如
- `'`或者`"`统一
- `if ()`里赋值检查
- 结尾分号检查

等

**Comment by softwhy** [comment]
不错的一个模板引擎

**Comment by xuexb** [comment]
啦啦啦

**Comment by softwhy** [comment]
额额

**Comment by softwhy** [comment]
你关闭了为什么我还能评论呢，怎么回事呢

**Comment by xuexb** [comment]
@softwhy 关闭了也能的啊

**Comment by softwhy** [comment]
那这个关闭代表了什么意思

**Comment by xuexb** [comment]
关了应该是意味着这个`bug`修复了，或者说这个问题得到了解决吧

**Comment by softwhy** [comment]
哦哦，原来如此
